-- Apply with a migration tool under separate database credentials. This migration
-- establishes immutable provenance and tenant-ready ownership boundaries.
CREATE SCHEMA IF NOT EXISTS app;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE app.approval_status AS ENUM ('draft', 'pending_approval', 'approved', 'disabled', 'revoked');
CREATE TYPE analytics.aggregation_behavior AS ENUM ('SUM', 'RATIO', 'WINDOWED_UNIQUE', 'SNAPSHOT', 'FUNNEL', 'EXTERNAL');
CREATE TYPE analytics.execution_status AS ENUM ('queued', 'running', 'succeeded', 'failed', 'incomplete', 'disabled');
CREATE TYPE analytics.freshness_state AS ENUM ('realtime', 'provisional', 'reconciling', 'stable');

CREATE TABLE app.organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app.companies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES app.organizations(id), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app.websites (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES app.companies(id), canonical_domain text NOT NULL, healthcare_eligibility text NOT NULL DEFAULT 'requires_review' CHECK (healthcare_eligibility IN ('approved','prohibited','requires_review')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(company_id, canonical_domain));
CREATE TABLE app.users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app.memberships (organization_id uuid NOT NULL REFERENCES app.organizations(id), user_id uuid NOT NULL REFERENCES app.users(id), role text NOT NULL CHECK (role IN ('agency_owner','agency_admin','agency_analyst','client_admin','client_viewer')), PRIMARY KEY (organization_id, user_id));

CREATE TABLE app.analytics_connections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES app.organizations(id), credential_type text NOT NULL CHECK (credential_type IN ('service_account','oauth')), credential_reference text NOT NULL, status app.approval_status NOT NULL DEFAULT 'pending_approval', disabled_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app.ga_properties (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), analytics_connection_id uuid NOT NULL REFERENCES app.analytics_connections(id), external_property_id text NOT NULL, display_name text, timezone text, currency_code text, metadata_json jsonb NOT NULL DEFAULT '{}', UNIQUE(analytics_connection_id, external_property_id));
CREATE TABLE app.ga_data_streams (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ga_property_id uuid NOT NULL REFERENCES app.ga_properties(id), external_stream_id text NOT NULL, display_name text, stream_type text, UNIQUE(ga_property_id, external_stream_id));
CREATE TABLE app.website_analytics_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), website_id uuid NOT NULL REFERENCES app.websites(id), analytics_connection_id uuid NOT NULL REFERENCES app.analytics_connections(id), ga_property_id uuid NOT NULL REFERENCES app.ga_properties(id), ga_stream_id uuid REFERENCES app.ga_data_streams(id), reporting_scope jsonb NOT NULL, effective_from date NOT NULL, effective_to date, status app.approval_status NOT NULL DEFAULT 'pending_approval', CHECK (effective_to IS NULL OR effective_to >= effective_from));
CREATE UNIQUE INDEX active_assignment_per_website ON app.website_analytics_assignments(website_id, effective_from) WHERE effective_to IS NULL AND status = 'approved';

CREATE TABLE app.measurement_contracts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text NOT NULL UNIQUE, industry text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app.measurement_contract_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contract_id uuid NOT NULL REFERENCES app.measurement_contracts(id), version integer NOT NULL, definition_json jsonb NOT NULL, approval_status app.approval_status NOT NULL DEFAULT 'draft', effective_from date, effective_to date, UNIQUE(contract_id, version));
CREATE TABLE app.website_measurement_contract_assignments (website_id uuid NOT NULL REFERENCES app.websites(id), measurement_contract_version_id uuid NOT NULL REFERENCES app.measurement_contract_versions(id), effective_from date NOT NULL, effective_to date, approval_status app.approval_status NOT NULL DEFAULT 'pending_approval', PRIMARY KEY(website_id, effective_from));
CREATE TABLE app.event_definitions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), contract_version_id uuid NOT NULL REFERENCES app.measurement_contract_versions(id), event_name text NOT NULL, definition_json jsonb NOT NULL, UNIQUE(contract_version_id,event_name));
CREATE TABLE app.metric_definitions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app.metric_definition_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), metric_definition_id uuid NOT NULL REFERENCES app.metric_definitions(id), version integer NOT NULL, aggregation analytics.aggregation_behavior NOT NULL, definition_json jsonb NOT NULL, approval_status app.approval_status NOT NULL DEFAULT 'draft', UNIQUE(metric_definition_id,version));
CREATE TABLE app.event_mappings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), website_id uuid NOT NULL REFERENCES app.websites(id), event_definition_id uuid NOT NULL REFERENCES app.event_definitions(id), metric_definition_version_id uuid NOT NULL REFERENCES app.metric_definition_versions(id), effective_from date NOT NULL, effective_to date, approval_status app.approval_status NOT NULL DEFAULT 'pending_approval');
CREATE TABLE app.report_definitions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app.report_definition_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), report_definition_id uuid NOT NULL REFERENCES app.report_definitions(id), version integer NOT NULL, definition_json jsonb NOT NULL, storage_mode text NOT NULL CHECK (storage_mode IN ('ALL_RETURNED_ROWS','TOP_N_SNAPSHOT')), approval_status app.approval_status NOT NULL DEFAULT 'draft', UNIQUE(report_definition_id,version));

CREATE TABLE analytics.sync_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id uuid NOT NULL REFERENCES app.website_analytics_assignments(id), started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, status analytics.execution_status NOT NULL, trigger text NOT NULL, error_code text, error_detail text);
CREATE TABLE analytics.sync_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), sync_run_id uuid REFERENCES analytics.sync_runs(id), assignment_id uuid NOT NULL REFERENCES app.website_analytics_assignments(id), report_definition_version_id uuid NOT NULL REFERENCES app.report_definition_versions(id), requested_start_date date NOT NULL, requested_end_date date NOT NULL, idempotency_key text NOT NULL UNIQUE, attempt_count integer NOT NULL DEFAULT 0, status analytics.execution_status NOT NULL DEFAULT 'queued', next_attempt_at timestamptz, error_code text, error_detail text);
CREATE TABLE analytics.report_executions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), assignment_id uuid NOT NULL REFERENCES app.website_analytics_assignments(id), report_definition_version_id uuid NOT NULL REFERENCES app.report_definition_versions(id), sync_job_id uuid REFERENCES analytics.sync_jobs(id), requested_start_date date NOT NULL, requested_end_date date NOT NULL, started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, request_hash text NOT NULL, response_hash text, property_time_zone text, currency_code text, empty_reason text, subject_to_thresholding boolean NOT NULL DEFAULT false, data_loss_from_other_row boolean NOT NULL DEFAULT false, sampling_metadata_json jsonb NOT NULL DEFAULT '{}', samples_read_count bigint, sampling_space_size bigint, schema_restrictions_json jsonb NOT NULL DEFAULT '{}', property_quota_json jsonb NOT NULL DEFAULT '{}', status analytics.execution_status NOT NULL, error_code text, error_detail text, UNIQUE(assignment_id, report_definition_version_id, requested_start_date, requested_end_date, request_hash));
CREATE TABLE analytics.daily_property_metrics (report_execution_id uuid NOT NULL REFERENCES analytics.report_executions(id), assignment_id uuid NOT NULL REFERENCES app.website_analytics_assignments(id), metric_definition_version_id uuid NOT NULL REFERENCES app.metric_definition_versions(id), metric_date date NOT NULL, value_numeric numeric, numerator_numeric numeric, denominator_numeric numeric, PRIMARY KEY(report_execution_id,metric_definition_version_id,metric_date));
CREATE TABLE analytics.daily_channel_metrics (report_execution_id uuid NOT NULL REFERENCES analytics.report_executions(id), assignment_id uuid NOT NULL REFERENCES app.website_analytics_assignments(id), channel text NOT NULL, metrics_json jsonb NOT NULL, PRIMARY KEY(report_execution_id,channel));
CREATE TABLE analytics.daily_page_metrics (report_execution_id uuid NOT NULL REFERENCES analytics.report_executions(id), assignment_id uuid NOT NULL REFERENCES app.website_analytics_assignments(id), landing_page text NOT NULL, metrics_json jsonb NOT NULL, PRIMARY KEY(report_execution_id,landing_page));
CREATE TABLE analytics.daily_event_metrics (report_execution_id uuid NOT NULL REFERENCES analytics.report_executions(id), assignment_id uuid NOT NULL REFERENCES app.website_analytics_assignments(id), event_name text NOT NULL, metric_date date NOT NULL, event_count bigint NOT NULL, PRIMARY KEY(report_execution_id,event_name,metric_date));
CREATE TABLE analytics.period_metric_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), report_execution_id uuid NOT NULL REFERENCES analytics.report_executions(id), assignment_id uuid NOT NULL REFERENCES app.website_analytics_assignments(id), metric_definition_version_id uuid NOT NULL REFERENCES app.metric_definition_versions(id), period_key text NOT NULL CHECK (period_key IN ('7d','28d','this_month','last_month','90d')), start_date date NOT NULL, end_date date NOT NULL, value_numeric numeric, numerator_numeric numeric, denominator_numeric numeric, freshness analytics.freshness_state NOT NULL, UNIQUE(report_execution_id,metric_definition_version_id,period_key));
CREATE TABLE analytics.data_quality_status (assignment_id uuid PRIMARY KEY REFERENCES app.website_analytics_assignments(id), freshness analytics.freshness_state, status text NOT NULL, details_json jsonb NOT NULL DEFAULT '{}', checked_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit.events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES app.organizations(id), actor_user_id uuid REFERENCES app.users(id), action text NOT NULL, target_type text NOT NULL, target_id uuid, detail_json jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());

-- Tenant RLS policy template. The API must set app.organization_id only after authentication.
ALTER TABLE app.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.websites ENABLE ROW LEVEL SECURITY;
CREATE POLICY company_tenant_isolation ON app.companies USING (organization_id = current_setting('app.organization_id', true)::uuid);
CREATE POLICY website_tenant_isolation ON app.websites USING (company_id IN (SELECT id FROM app.companies));
