import type { AcquisitionData, ConversionData, GoalsData, HealthData, Identity, LandingPagesData, MembershipData, OnboardingChecklist, OnboardingWorkflow, OverviewData, Period, PortfolioData, PortalResources, SyncStatus } from './types';
const request = async <T>(path: string, init?: RequestInit): Promise<T> => { const response = await fetch(path, { credentials: 'same-origin', headers: { Accept: 'application/json', ...(init?.body ? { 'Content-Type': 'application/json' } : {}) }, ...init }); if (!response.ok) throw new Error((await response.text()) || ('Request failed (' + response.status + ')')); return response.status === 204 ? undefined as T : await response.json() as T; };
const withPeriod = (path: string, period: Period) => path + '?period=' + encodeURIComponent(period);
export const api = {
  identity: () => request<Identity>('/api/portal/identity'), resources: () => request<PortalResources>('/portal/access/resources'),
  continueAccess: (websiteId?: string, companyId?: string) => request<{ redirect: string }>('/portal/access/continue?website_id=' + encodeURIComponent(websiteId || '') + '&company_id=' + encodeURIComponent(companyId || ''), { method: 'POST' }),
  overview: (companyId: string, period: Period) => request<OverviewData>(withPeriod('/api/companies/' + encodeURIComponent(companyId) + '/overview', period)),
  acquisition: (websiteId: string, period: Period) => request<AcquisitionData>(withPeriod('/api/websites/' + encodeURIComponent(websiteId) + '/acquisition', period)), conversion: (websiteId: string, period: Period) => request<ConversionData>(withPeriod('/api/websites/' + encodeURIComponent(websiteId) + '/conversion', period)),
  landingPages: (websiteId: string, period: Period) => request<LandingPagesData>(withPeriod('/api/websites/' + encodeURIComponent(websiteId) + '/landing-pages', period)), health: (websiteId: string, period: Period) => request<HealthData>(withPeriod('/api/websites/' + encodeURIComponent(websiteId) + '/measurement-health', period)),
  sync: (websiteId: string) => request<SyncStatus>('/api/websites/' + encodeURIComponent(websiteId) + '/sync-status'), goals: (websiteId: string) => request<GoalsData>('/api/websites/' + encodeURIComponent(websiteId) + '/goals'), pdfUrl: (websiteId: string, period: Period) => withPeriod('/api/websites/' + encodeURIComponent(websiteId) + '/reports/pdf', period),
  portfolio: (period: Period) => request<PortfolioData>(withPeriod('/api/portfolio/summary', period)), memberships: () => request<MembershipData>('/api/memberships'),
  workflow: (id: string) => request<OnboardingWorkflow>('/api/onboarding/workflows/' + encodeURIComponent(id)), checklist: (id: string) => request<OnboardingChecklist>('/api/onboarding/workflows/' + encodeURIComponent(id) + '/checklist'),
  createWorkflow: (body: unknown) => request<OnboardingWorkflow>('/api/onboarding/workflows', { method: 'POST', body: JSON.stringify(body) }), governance: (id: string, body: unknown) => request<OnboardingWorkflow>('/api/onboarding/workflows/' + encodeURIComponent(id) + '/governance', { method: 'POST', body: JSON.stringify(body) }),
  connection: (id: string, body: unknown) => request<OnboardingWorkflow>('/api/onboarding/workflows/' + encodeURIComponent(id) + '/connections', { method: 'POST', body: JSON.stringify(body) }), firstSync: (id: string, body: unknown) => request<OnboardingWorkflow>('/api/onboarding/workflows/' + encodeURIComponent(id) + '/first-sync', { method: 'POST', body: JSON.stringify(body) }), clientAccess: (id: string, body: unknown) => request<OnboardingWorkflow>('/api/onboarding/workflows/' + encodeURIComponent(id) + '/memberships', { method: 'POST', body: JSON.stringify(body) }),
};
